"""Add books, readers and borrowed_books tables

Revision ID: 19544301d44e
Revises: 96ecee4359be
Create Date: 2025-05-30 10:01:25.676782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19544301d44e'
down_revision: Union[str, None] = '96ecee4359be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_index(op.f('ix_borrowed_books_id'), 'borrowed_books', ['id'], unique=False)
    op.alter_column('readers', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('readers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(op.f('readers_email_key'), 'readers', type_='unique')
    op.create_index(op.f('ix_readers_email'), 'readers', ['email'], unique=True)
    op.create_index(op.f('ix_readers_id'), 'readers', ['id'], unique=False)
    op.create_index(op.f('ix_readers_name'), 'readers', ['name'], unique=False)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readers_name'), table_name='readers')
    op.drop_index(op.f('ix_readers_id'), table_name='readers')
    op.drop_index(op.f('ix_readers_email'), table_name='readers')
    op.create_unique_constraint(op.f('readers_email_key'), 'readers', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('readers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('readers', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_borrowed_books_id'), table_name='borrowed_books')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    # ### end Alembic commands ###
